#!/bin/sh
cd `dirname $0`
#../src/slaw -n .:../src $*
#../src/slaw -n .:../src $* -u Cmdenv -c SlawMatlab
../src/slaw -n .:../src $* -u Cmdenv -c FlightLengthMatlab
#../src/slaw -n .:../src $* -u Cmdenv -c ConnectivityTest
#../src/slaw -n .:../src $* -u Cmdenv -c TripRecorder
# for shared lib, use: opp_run -l ../src/template -n .:../src $*
