#!/bin/sh
cd `dirname $0`
#../src/slaw -n .:../src $*
../src/slaw -n .:../src $* -u Cmdenv -c SlawMatlabValidation
#../src/slaw -n .:../src $* -u Cmdenv -c RandomArea
#../src/slaw -n .:../src $* -u Cmdenv -c ConnectivityTest
#../src/slaw -n .:../src $* -u Cmdenv -c TripRecorder
#../src/slaw -n .:../src $* -u Cmdenv -c TripAnalizer
# for shared lib, use: opp_run -l ../src/template -n .:../src $*
